name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Report build failure
        run: echo "Build failed!" > build_failure_report.txt
        if: failure() 

      - name: Upload Build Failure Report
        uses: actions/upload-artifact@v3  # Updated to v3
        if: failure()
        with:
          name: build-failure-report
          path: build_failure_report.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy application
        run: echo "Deploying application..."

      - name: Generate deploy success report
        run: echo "Deployment was successful." > deploy_report.txt

      - name: Generate deploy failure report
        run: echo "Deployment failed." > deploy_failure_report.txt
        if: failure()

      - name: Upload Deployment Report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: deploy-report
          path: deploy_report.txt

      - name: Upload Deployment Failure Report
        uses: actions/upload-artifact@v3  # Updated to v3
        if: failure()
        with:
          name: deploy-failure-report
          path: deploy_failure_report.txt
