name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm start

    # Generate a success or failure report
    # - name: Build success report
    #   if: success()
    #   run: |
    #     echo "Build was successful!" > build-report.txt
    #     echo "Application started and running properly."

    # - name: Build failure report
    #   if: failure()
    #   run: |
    #     echo "Build failed!" > build-report.txt
    #     echo "Check the logs for more details."

    # Deployment step (optional, customize according to your deployment)
    - name: Deploy to Web (Optional)
      run: echo "Deployment step goes here."

    # Upload build report artifact
    - name: Upload Build Report
      uses: actions/upload-artifact@v3
      with:
        name: build-report
        path: build-report.txt
