name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow only for pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check for build success
        run: echo "Build completed successfully."
        if: success() # This step runs if the build succeeds

      - name: Report build failure
        run: echo "Build failed!" > build_failure_report.txt
        if: failure() # This step runs if the build fails

      - name: Upload Build Failure Report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-failure-report
          path: build_failure_report.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Simulate deployment commands here

      - name: Generate deploy success report
        run: echo "Deployment was successful." > deploy_report.txt

      - name: Generate deploy failure report
        run: echo "Deployment failed." > deploy_failure_report.txt
        if: failure() # This runs if the deploy fails

      - name: Upload Deployment Report
        uses: actions/upload-artifact@v2
        with:
          name: deploy-report
          path: deploy_report.txt

      - name: Upload Deployment Failure Report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: deploy-failure-report
          path: deploy_failure_report.txt
